### ISSUE TITLE
Edit own Events ✨

### ISSUE THREAD

**Issue by EdonaLlesh1** [jessicareinh/capstone-event-app#17]
## Value proposition

As a user
I want to be able to edit my added events in case I want to change something
so that I can be more flexible in what I write there.

## Description

![Image](https://github.com/jessicareinh/capstone-event-app/assets/152086528/2e3b943e-417d-4a0d-9d5e-f99d6a7af408)

## Acceptance criteria
- [ ] When clicking on one of our events, on the detailed page that appears, there is an "Edit" button available, allowing us to edit that event
- [ ]  After clicking the "Edit" button, we can make the necessary changes to the event.
- [ ] Once we have made the desired changes, we click the "Save" button.
- [ ] After saving, we are redirected back to the "My Events" page with the edited event displayed.

## Tasks

- [ ] integrate edit button on the details page.
- [ ] Write a new handler function for edit .
- [ ] Integrate a save button on the details page.
- [ ]  Write a new handler function for save .

**Comment by Melonexx** [comment]
I'm really interested in the outcome of this user story. looks great btw 🎉😸

**Comment by JessicaLoers** [comment]
**One additional comment 🫣**

As a further acceptance criteria, it would make sense to cancel the edit mode.
