### ISSUE TITLE
US  Responsiveness ✨

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#18]
##Value proposition
As a user
I want to be able to access the app from every device
to stay informed about upcoming events no matter where I am.

##Description

![Image](https://github.com/jessicareinh/capstone-event-app/assets/148791371/ac2590e4-983f-4b04-938b-de70f57434fa)

##Acceptance Criteria

- [ ] depending on which device I am, the page should be readable
- [ ] when I open a window and make it smaller/or bigger, the app should respond to this action and depict the events also in a smaller or bigger way

##Tasks

- [ ] create the feature branch responsiveness
- [ ] add media queries for different devices

**Comment by somaSeb** [comment]
The term "device" is to broad. What kind of device do you refer to here? Please specify e.g. resolution ranges

**Comment by jessicareinh** [comment]
updated!
