### ISSUE TITLE
add consistent styling in css

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#29]
## Value proposition

As a user 
I want to have styled application and color schemes
so that I have a better overview of the page and also a better User Experience

## Description

![Image](https://github.com/jessicareinh/capstone-event-app/assets/148791371/530804f6-4664-45fa-aac1-83468c2b2010)

 
## Acceptance Criteria

- [ ] implement color scheme
- [ ] buttons should look consistent 
- [ ] it should be visible that we work with primary, secondary colors

## Tasks

- [ ] implement the app colors
- [ ] refactor styling in css files
- [ ] choose primary, secondary colors

**Comment by Melonexx** [comment]
Refactoring the code css-wise is always helpful for structuring your files! Just a little reminder that the value proposition has a  given format 3 lines -> as a ... <br> i want to... <br> so that ... (Wouldn't have made this comment if andrea didn't tell us... 😅✨💖
