### ISSUE TITLE
US Loading Animation

### ISSUE THREAD

**Issue by EdonaLlesh1** [jessicareinh/capstone-event-app#31]
## Value proposition

As a user
I want to see a Loading Animation while waiting for content to load 
so that I am informed that the app is processing my request. 

## Description

![Image](https://github.com/jessicareinh/capstone-event-app/assets/152086528/d4b0098a-ca4e-4ae7-a729-2ccad9f69406)

## Acceptance Criteria

- [ ] the loading animation should appear while the API Data is being fetched
- [ ] The Loading Animation should be visually appealing and clearly indicate that the application is processing.
- [ ] The animation should be positioned centrally or in a prominent location on the screen to ensure visibility.
- [ ] The Loading Animation should disappear once the content is fully loaded.

## Tasks

- [ ] create a loading animation component
- [ ] import the component into the the _app.js and render the animation, if the loading state is true

**Comment by Miriam-Voelkl** [comment]
you could add a pre-defined loading time so that the loading animation is visible for long enough that the user can register it (seeing a loading animation for only 0.3s or something would be a bit confusing because you can't really tell what's happening). apart from that a great feature, looking forward to your animation ✨
