### ISSUE TITLE
Random Event Highlight

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#32]
## Value proposition
As a user 
I want to get an event suggestion
In order to get inspired and attend different kinds of events.

## Acceptance criteria

- [ ] by clicking on event highlight in the burger menu I want to get to the Highlight page

- [ ] this highlight page shows a Details page for the suggested event containing:

-  the event's picture 
- the event's name 
- the date 
- the location
- starting time 
- category
- if the API offers a description, it should be displayed in the card 

- [ ] by clicking on "Get other Highlight" it should render a different random event with the same details

## Tasks

- [ ] create the feature branch event-highlight
- [ ]
