### ISSUE TITLE
Event List

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#4]
## Value proposition
As a user 
I want to see a list of all upcoming events
In order to quickly discover and explore the latest events
## Acceptance criteria

- [ ] On the homepage, there is a list of upcoming events displayed

- [ ] Each event in the list includes the following details:
- [ ] The name of the event
- [ ] The image of the event
- [ ] The date of the event
- [ ] The location of the event
- [ ] If there is an issue loading the event data from the source, an error message is displayed to the user
- [ ] The event list is vertically scrollable

## Tasks

- [ ] Create the feature branch event-list
- [ ] Fetch a list of all upcoming events from the Ticketmaster API
- [ ] Implement the error handling logic to display an error message if there's an issue loading event data from the API
- [ ] Create the component event, which renders:
- [ ]  The name of the event
- [ ]  The poster image of the event
- [ ]  Create the component EventList
- [ ]  Map through the fetched list of events and render a Event component for each movie
- [ ]  Render the EventList component in the index.js

**Comment by ahohnsen** [comment]
Nicely done! 🙌
