### ISSUE TITLE
US Event-Details-Page

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#5]
## Value proposition
As a user
I want to be able to view detailed information about each event,
In order to make an informed decision about which event I want to attend.

## Acceptance criteria

- [ ]  When the user selects an event from the list on the homepage, they are directed to a event detail page
- [ ]  On the event details page, the user sees the following information:
- [ ]  the event's picture
- [ ]  the event's name 
- [ ]  the date of the event
- [ ] the location of the event
- [ ] a detailed description of the event, providing insights about what is going to happen there
- [ ] The user can return to the homepage by clicking a dedicated "Back to Home" button located on the top of the event details page

 

## Tasks

- [ ] Create the feature branch event-details-page
- [ ]  Create the event details page pages/events/[id].js
- [ ]  Render the event's poster, title, release date and description
- [ ]  Add the Link component to navigate back to the homepage
- [ ]  Update the Event component
- [ ]  Add the Link component to navigate to the details page

**Comment by StellaKakarali** [comment]
Looks great and the planing makes sense!  Only one thing: In your acceptance criteria you named your Back-Button "Back to Home", but in the description it says "Back".
