### ISSUE TITLE
US - Add Favourites

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#6]
## Value proposition
As a user
I want to have the ability to add my favourite events to a favourite list,
In order to keep track of the events I'm interested in.

## Acceptance criteria
- [ ]  There is a navigation bar that allows the user to switch between the homepage and favourites
- [ ]  The navigation bar is at the top
- [ ]  The link to the current page in the navigation bar is visually highlighted, to indicate the user's current location in the app
- [ ]  On the event details page:
- [ ]  There is a heart-shaped-button that allows the user to add the event to their favourites
- [ ]  If the event is already on the user's favourites, the user can unadd the event by clicking on the button
- [ ]  On the favourites page:
- [ ]  The favourites-list displays all events that the user has added, showing their names, pictures, location and date
- [ ]  When the user selects an event from the favourites, they are directed to the event detail page
- [ ]  If the favourites-list  is empty, a message is displayed on the favourites page, indicating that there are no favourites yet
- [ ]  The favourites page is vertically scrollable

## Tasks

- [ ]  Create the feature branch favourites
- [ ]  Create a Navigation component
- [ ]  add a Link component for the homepage and the favourites
- [ ]  highlight the link to the current page
- [ ]  Create a Layout component
- [ ]  add the Navigation component
- [ ]  Render the Layout component in the _app.js
- [ ]  Update the event details page pages/events/[id].js
- [ ]  Include a heart-shaped-button 
- [ ]  Implement the logic that changes the button label if the event is already in the favourites list
- [ ]  Update the app.js
- [ ]  Create a useState for the favourites
- [ ]  Implement a function that adds or removes events from the user's favourites
- [ ]  Create the page pages/favourites.js
- [ ]  Reuse the EventList component to display the events on the favourites
- [ ]  Display a message on the favourites page if it's empty, indicating that there are no added favourites.

**Comment by ahohnsen** [comment]
Just one thing:

You are writing about a navigation but in your wireframes there is none 🤔

**Comment by Aytac-Karkin** [comment]
Same note as Andrea, otherwise nice 👍

**Comment by JessicaLoers** [comment]
Hey Team 
I see that you have integrated the navigation into the wire frame. 💯

However, there's now also a link to a page _"My Events"_.  As far as I understand it, you don't have this page yet. For this reason, I would like to recommend that you remove this link from the navigation (i.e. from the wireframe). 

Otherwise tip top, good work.
