### ISSUE TITLE
US - Add Events

### ISSUE THREAD

**Issue by EdonaLlesh1** [jessicareinh/capstone-event-app#8]
## Value proposition

As a user
I want to add my own events
In order to  plan and see all upcoming events for me.
## Description

![Image](https://github.com/jessicareinh/capstone-event-app/assets/152086528/18c3dd9f-23a9-4565-a679-353d5abd2f99)

## Acceptance criteria

- [ ] The user should see a prominent and easily accessible "Add Event" button on the main screen.
- [ ] Upon tapping the "Add Event" button, the app should smoothly transition to a new screen where I can input details for the event.
- [ ]  Event-details:
- [ ] Name
- [ ] Date
- [ ] City
- [ ] Description (optional)
- [ ] Add to Favourite
- [ ] After entering the event details, there  should be a "Save" or "Add Event" button to save the event in my personal page.
- [ ]  After saving the event, a new page or modal should open, displaying the list of events I have created.
- [ ] Each event in the list should have an option to be added to a "Favourite" list.

## Tasks
- [ ]  Create the feature branch Add-Events
- [ ] Create a AddEvent component , that will serve as the form for adding events.
- [ ] Design the component to include input fields for event name, date, city, and an optional description.
- [ ]  Integrate the FavouriteButton component within the AddEvent component.

**Comment by Miriam-Voelkl** [comment]
Looks good 🐝 Two optional suggestions: 1. if you don't have a separate user story for the event handling, you could add it to your tasks here. 2. to me, it wasn't immediately clear that the heart on the "add your event" page is a button, I thought it was part of the headline because it's part of the "your favorite events" headline as well. to me, it would be clearer that the heart is a button if it was somewhere else on the page

**Comment by SophiaZett** [comment]
hey team, looks good so far!

I just have one suggestion:

unfortunately its a bit confusing at first point:
 _by clicking on the ADD Button the user should see the page "My Events"_

is your ADD button the "my event" button on the homepage?
