### ISSUE TITLE
US - Delete Function

### ISSUE THREAD

**Issue by jessicareinh** [jessicareinh/capstone-event-app#9]
## Value proposition
As a user
I want to be able to delete my added events in case they are cancelled
In order to have an accurate overview of my upcoming events.
## Acceptance criteria
- [ ] there is a button with a trash icon on every detail page of the events I have added
- [ ] when clicking the button the usier is asked to confirm the deletion
- [ ] on this confirm-pop-up the user can either cancel the deletion and gets redirected to the details page 
- [ ] or the user can confirm the deletion and is redirected to the overview page
- [ ] the deleted event is not displayed on the overview page anymore

## Tasks

- [ ] create new DELETE route in api folder 
- [ ] integrate delete button on the details page
- [ ] write new handler function for deletion
- [ ] integrate pop up

**Comment by StellaKakarali** [comment]
Looks great!

**Comment by ahohnsen** [comment]
Just a small hint: It's a modal, not a pop-up.

In your tasks, you are writing that you will create an api route for DELETE. You are not working with a backend here and therefore do not need an api route 🤔 As far as I know, you are saving your events in a `useState`, so when you delete an event, you are just updating your state.

**Comment by jessicareinh** [comment]
all updatet :)
